-- 1. Create the posts table for the boards
CREATE TABLE public.posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    content text NOT NULL,
    board text NOT NULL,
    image_url text
);

-- 2. Enable Row Level Security (RLS)
-- For a 4-chan style board, we'll allow anyone to read and insert
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" ON public.posts
    FOR SELECT USING (true);

CREATE POLICY "Allow anonymous insert access" ON public.posts
    FOR INSERT WITH CHECK (true);

-- 3. Enable Realtime for the posts table
-- This is critical for the "4-chan style" instant updates
begin;
  -- remove the table from the realtime publication
  drop publication if exists supabase_realtime;

  -- re-create the publication including the posts table
  create publication supabase_realtime for table public.posts;
commit;
