-- Create table for GPS telemetry
CREATE TABLE public.location_telemetry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    device_name text,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);

-- Enable RLS
ALTER TABLE public.location_telemetry ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (for the mobile app)
CREATE POLICY "Allow anonymous inserts" ON public.location_telemetry
    FOR INSERT WITH CHECK (true);

-- Allow public reads (for the website map)
CREATE POLICY "Allow public read" ON public.location_telemetry
    FOR SELECT USING (true);
